<div class="checkout-payment-method">
    <h4><?php echo $this->__('Select Payment Method')?></h4>
    <div class="step-content">
        <?php
        $methods = $this->getMethods();
        $oneMethod = count($methods) <= 1;
        ?>
        <?php if (empty($methods)): ?>
            <dt>
                <?php echo $this->__('No Payment Methods') ?>
            </dt>
        <?php else:
            foreach ($methods as $_method):
                $_code = $_method->getCode();
                ?>
                <dt id="dt_method_<?php echo $_code ?>">
                    <?php if(!$oneMethod): ?>
                        <input id="p_method_<?php echo $_code ?>" value="<?php echo $_code ?>" type="radio" name="payment[method]" title="<?php echo $this->escapeHtml($_method->getTitle()) ?>" onclick="shippingPayment.switchMethod('<?php echo $_code ?>')"<?php if($this->getSelectedMethodCode()==$_code): ?> checked="checked"<?php endif; ?> class="radio" />
                    <?php else: ?>
                        <span class="no-display"><input id="p_method_<?php echo $_code ?>" value="<?php echo $_code ?>" type="radio" name="payment[method]" checked="checked" class="radio" /></span>
                        <?php $oneMethod = $_code; ?>
                    <?php endif; ?>
                    <label for="p_method_<?php echo $_code ?>"><?php echo $this->escapeHtml($this->getMethodTitle($_method)) ?> <?php echo $this->getMethodLabelAfterHtml($_method) ?></label>
                </dt>
                <?php if ($html = $this->getPaymentMethodFormHtml($_method)): ?>
                <dd id="dd_method_<?php echo $_code ?>">
                    <?php echo $html; ?>
                </dd>
            <?php endif; ?>
            <?php endforeach;
        endif;
        ?>

        <?php echo $this->getChildChildHtml('additional'); ?>
    </div>
</div>
<script type="text/javascript">
    //<![CDATA[
    <?php echo $this->getChildChildHtml('scripts'); ?>
    shippingPayment.init();
    <?php if (is_string($oneMethod)): ?>
    shippingPayment.switchMethod('<?php echo $oneMethod ?>');
        <?php endif; ?>
    //]]>
</script>
